version: '3.0'

services:

    users-db:
        container_name: flask-users-db
        build: ./project/db
        ports:
            - 5435:5432 # expose ports - HOSTS:CONTAINER
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: exit 0

    users-service:
        container_name: flask_users_management
        build: .
        volumes:
            - .:/app
        ports:
            - 5001:5000 # expose ports HOST:CONTAINER
        environment:
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
        depends_on:
            - users-db
        links:
            - users-db

    nginx:
        container_name: nginx
        build: ./nginx/
        restart: always
        ports:
            - 80:80
        depends_on:
            - users-service
        links:
            - users-service